### ISSUE TITLE
game stop progress after I close the player web tab on iphone 6s

### ISSUE THREAD

**Issue by ritsukaBin** [engagementgamelab/emerging-citizens#82] opened 2016-07-20 16:56 UTC
<img width="1414" alt="screen shot 2016-07-20 at 12 43 43 pm" src="https://cloud.githubusercontent.com/assets/20562141/16995149/b5fd613c-4e78-11e6-9ae2-8d767dfd0339.png">

I close the web tab on iphone 6s after submitted hashtag, then after the other two tab on desktop finished submitted hashtag, the game stop progressing, it stay in the page of "make up hashtag" forever.

environment: two players on mac os, chrome; one player on iphone 6s, ios9.3.2, safari

UPDATE: 
if one player quit in the middle the game, when it comes to the hashtag submission session, the game will stop progress to the next stage.

**Comment by jpailthorpe** [comment] 2016-09-06 15:53
In a situation where a player drops from the game mid game, the game should progress on based on the timer regardless. @johnnycrich want to check to make sure this is the case? Also it looks like this issue has three players, but I was slightly concerned about what happens when there is only two players, and one player drops. This is a separate case, but in that situation, it should most likely cancel the game completely.

**Comment by johnnycrich** [comment] 2016-09-06 21:52
I have resolved this issue partially but still need to work on one or two sub-issues before this is resolved.

**Comment by johnnycrich** [comment] 2016-09-13 18:49
Should be fixed as of commit 2953101a8264b523298f7dd2afe3828c21fb6ad6. Please confirm.

**Comment by johnnycrich** [comment] 2016-09-26 20:32
Still waiting on QA confirmation

**Comment by jpailthorpe** [comment] 2016-09-26 21:32
@ritsukaBin next time you come in please prioritize checking this. if you cant  reproduce, please comment as fixed and moved to done

**Comment by ritsukaBin** [comment] 2016-09-28 19:19
Setting: 
iphone 6s safari / Mac chrome / ipod safari

Process: 
ip6s submit first-- then mac chrome submits--next close webpage on ip6s--submit via ipod--no proceeding to voting till counting end--on voting page ip6s's submission still there
<img width="926" alt="screen shot 2016-09-28 at 3 15 55 pm" src="https://cloud.githubusercontent.com/assets/20562141/18928562/a91c9b48-858e-11e6-86b5-de13c672ad63.png">

--game went into scoring--suddenly disconnected
<img width="796" alt="screen shot 2016-09-28 at 3 17 59 pm" src="https://cloud.githubusercontent.com/assets/20562141/18928595/c3d76eea-858e-11e6-8aed-2220a738a002.png">

--game page on ipod and mac freeze at this page, no automatic refresh
<img width="393" alt="screen shot 2016-09-28 at 3 18 28 pm" src="https://cloud.githubusercontent.com/assets/20562141/18928620/e34a5bde-858e-11e6-94c4-a8240820baeb.png">

**Closed** 2016-10-31 17:11 UTC
Labels: bug, critical, global, HTYI, reproduce me
