### ISSUE TITLE
HTYI: Submitting Special Characters: no error message, game continues for everyone except that one player

### ISSUE THREAD

**Issue by beccachairin** [engagementgamelab/emerging-citizens#109] opened 2016-08-01 16:16 UTC
I wanted to see what would happen if a user (Morgan) submitted a special character as part of their response: 
![screen shot 2016-08-01 at 11 58 09 am](https://cloud.githubusercontent.com/assets/20775665/17300426/61ef88f6-57e0-11e6-9bb4-bf5eb6cb4c4d.png)

Once I pressed "post", Morgan's screen stayed where it was and didn't advance to the next page. It appeared as if the answer wasn't posted. However, the remaining players were able to continue playing the game and Morgan's answer was posted. 
![screen shot 2016-08-01 at 11 58 38 am](https://cloud.githubusercontent.com/assets/20775665/17300492/a1f4376c-57e0-11e6-9321-0a9534e6ecae.png)
![screen shot 2016-08-01 at 11 58 29 am](https://cloud.githubusercontent.com/assets/20775665/17300495/a70bfaf0-57e0-11e6-84aa-bfd88572ca77.png)

The next round, all other players were able to submit hashtags during this round but Morgan's screen stayed stuck on the first screenshot. As the game continued, it submitted Morgan's answer as "#level" by default. Other players were even able to select this answer and Morgan was able to score points for her automatically submitted answer. Meanwhile, Morgan wasn't able to select any hashtags for any additional rounds. 
![screen shot 2016-08-01 at 12 01 21 pm](https://cloud.githubusercontent.com/assets/20775665/17300590/03c24088-57e1-11e6-8b3b-8f0fa1240bd0.png)

Next round, it submitted "#destruction" for Morgan, even though I erased the last answer and tried to submit "policebrutalitysux". Again, Morgan was able to score points if other players selected "destruction". I don't know where the program is getting these words from??
![screen shot 2016-08-01 at 12 12 59 pm](https://cloud.githubusercontent.com/assets/20775665/17300756/b6405740-57e1-11e6-865f-d17d07ff61fd.png)
![screen shot 2016-08-01 at 12 13 28 pm](https://cloud.githubusercontent.com/assets/20775665/17300757/b9d1d73a-57e1-11e6-91ef-29a49abe0b81.png)
![screen shot 2016-08-01 at 12 13 57 pm](https://cloud.githubusercontent.com/assets/20775665/17300758/bc2273be-57e1-11e6-9f44-d961e5d62025.png)

Overall, not sure if it was the special character that I tried to submit way back in the day that made all this happen or if it's a separate issue.

**Comment by beccachairin** [comment] 2016-08-01 16:38
update: submitted an apostrophe in the middle of a hashtag and it went through no problem. Meanwhile, Morgan is still submitting random answers (#butcher??). 
![screen shot 2016-08-01 at 12 36 59 pm](https://cloud.githubusercontent.com/assets/20775665/17301395/d2a8df26-57e4-11e6-8c4f-43607219a3be.png)

**Comment by esalling23** [comment] 2016-08-02 21:43
cannot reproduce - closing for now

**Closed by esalling23** 2016-08-02 21:43 UTC
Labels: cannot-reproduce, HTYI
