### ISSUE TITLE
WG: game doesn't register that 2nd and 3rd players to reach target article have completed the round, also timer goes into negative values

### ISSUE THREAD

**Issue by beccachairin** [engagementgamelab/emerging-citizens#126] opened 2016-08-02 18:28 UTC
I had 3 desktop players open for this game, registered in order from 1-3. The starting prompt was "postcolonialism", with the article to find being "Frantz Fanon". The starting articles for each player were: 
1. (Kim) - postcolonial literature
2. (Kanye) - postcolonialism
3. (North) - postcolonialism

The first person to reach the target article was Kim, reached it in one click (postcolonial literature > Frantz Fanon). The winning screen for a player popped up as usual, no problem. 
![screen shot 2016-08-02 at 2 07 08 pm](https://cloud.githubusercontent.com/assets/20775665/17339814/9a8da57c-58bb-11e6-92d2-2abadd42d3fb.png)

Now, there are at least 60 seconds left on the clock, which gives the other two players time to find the correct article. I play as Kanye (player 2) next, and the link path I take to get to the target article is postcolonialism > colonialism > Frantz Fanon. However, once I click on Frantz Fanon, instead of the screen popping up that says I have completed the round, instead I am taken to the page itself. 
![screen shot 2016-08-02 at 2 07 05 pm](https://cloud.githubusercontent.com/assets/20775665/17339945/2f2b8e10-58bc-11e6-891b-74dd35fc4e6e.png)

I try the same link path for North (player 3), and get the same result. I even try clicking to other pages and clicking back to the target article to see if it registers that Kanye and North have completed the round, but again it just opens the Frantz Fanon page. (The link path I am clicking here is Frantz Fanon > French philosophers > Frantz Fanon.)

Meanwhile, the timer has run out, but instead of ending the round, the timer begins to count backwards in negative numbers?? As I was typing this the timer has now reached -13 minutes and the round has not advanced. 
![screen shot 2016-08-02 at 2 07 11 pm](https://cloud.githubusercontent.com/assets/20775665/17340184/22b984a6-58bd-11e6-99cf-162deb6b1269.png)
![screen shot 2016-08-02 at 2 08 43 pm](https://cloud.githubusercontent.com/assets/20775665/17340187/26268076-58bd-11e6-819d-4a04ef0b9bbe.png)

**Comment by jpailthorpe** [comment] 2016-09-06 15:38
hmm...Unsure if when saying that "the winning screen popped up as usual" means that the results screen came up when all players were finished (like it should) on the group screen or if the winning screen IMMEDIATELY came up in the users screen. 

In terms of the timer, I assuming this has something to do is the back browser elements.

**Comment by johnnycrich** [comment] 2016-09-07 15:52
Unable to repro. May have been resolved by fix for #140 .

**Comment by mattwbenson** [comment] 2016-09-14 20:47
Unable to reproduce

**Closed by mattwbenson** 2016-09-14 20:47 UTC
Labels: bug, cannot-reproduce, reproduce me, WikiGeeks
