### ISSUE TITLE
HTYI: color bar for two of the eight vote options disappear on mobile devices 

### ISSUE THREAD

**Issue by ritsukaBin** [engagementgamelab/emerging-citizens#124] opened 2016-08-02 15:27 UTC
environment and setting: 8 players (3 on Mac chrome, 3 on Mac safari, 2 on iPhone 6s safari)

color bar gone on iPhone 6s
![img_7276](https://cloud.githubusercontent.com/assets/20562141/17334339/e7cb6062-58a3-11e6-8101-bc2d6dad8783.PNG)
![img_7276](https://cloud.githubusercontent.com/assets/20562141/17334340/e9954e76-58a3-11e6-96c0-c23bc76e9b07.PNG)

**Comment by esalling23** [comment] 2016-08-02 17:05
duplicate of #43

**Comment by ritsukaBin** [comment] 2016-08-02 17:45
In 7 players case (3 on mac chrome, 3 on mac safari, 1 on iphone 6s safari), only the color background for first voting option disappears
![img_7287](https://cloud.githubusercontent.com/assets/20562141/17338889/5b4bebc0-58b7-11e6-8e5e-b7c8410112d1.PNG)

**Closed** 2016-08-02 19:30 UTC
Labels: duplicate, HTYI, low-priority
