### ISSUE TITLE
WG: iPad submits on slight delay, can break timer and make unplayable

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#136] opened 2016-08-10 15:00 UTC
Because the iPad takes an extra half-second or so to submit a starting page than the other platforms, if a page is submitted right at the last second, the hub-screen timer will fail to load.

1.Devices join game (Android/Samsung Tablet, iPad, Chrome Desktop window)
2. Submitted starting article for Tablet, submitted same article on iPad at last possible second, did not submit on desktop.
3. When hub screen loads with the target article, timer is gone. 

![screen shot 2016-08-10 at 10 57 36 am](https://cloud.githubusercontent.com/assets/12397944/17558752/a659a0de-5ee9-11e6-820a-6daf0e8f65a1.png)

**Comment by mattwbenson** [comment] 2016-08-10 15:01
In some instances of this bug, the iPad will not allow the player to follow through links on their device, but stay frozen on the starting page, but this does not happen every time.

**Comment by jpailthorpe** [comment] 2016-09-06 15:42
We might need to have a "buffer time" where the delay is accounted for?

**Comment by jpailthorpe** [comment] 2016-09-26 21:13
Need to verify

**Comment by esalling23** [comment] 2016-09-27 19:36
cannot reproduce - closing for now unless can be reproduced

**Closed by esalling23** 2016-09-27 19:36 UTC
Labels: bug, critical, WikiGeeks
