### ISSUE TITLE
HTYI: Replace avatar 8 icon with new different version

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#222] opened 2016-11-09 22:05 UTC
![screen shot 2016-11-09 at 5 05 00 pm](https://cloud.githubusercontent.com/assets/12397944/20156533/ab5da77c-a69e-11e6-8447-886e4b8e1d54.png)

Players 4 and 5 both have the same icon.

**Comment by esalling23** [comment] 2016-11-11 19:59
Looks like the 8th icon was never made - there's a duplicate of this icon both in the GoogleDrive and on our Cloudinary account.

**Comment by jpailthorpe** [comment] 2016-11-16 01:25
https://drive.google.com/open?id=0B2iJJeD7RJtgcmlFRTR4NEo3aE0

I made a 8th avatar based on Aidan's design. We can update with a new icon set in the future. For now lets use this at least for the purpose of differentiating between players.

**Comment by jpailthorpe** [comment] 2016-11-16 01:29
![avatar8](https://cloud.githubusercontent.com/assets/10051544/20331242/2e2432b6-ab72-11e6-8ccd-69f580a3a221.png)

**Comment by mattwbenson** [comment] 2016-11-18 16:58
Still seeing the doubled icon, it's just doubling for icon 1 and 4 now.

**Closed** 2016-11-18 17:14 UTC
Labels: HTYI, UI/UX
