### ISSUE TITLE
Hashtag duplicates on moderator screen if player submits real hashtag

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#26] opened 2016-05-12 15:38 UTC
Both the real hashtag and the player-created "real hashtag" appear on the moderator screen, but only the real hashtag appears on the voting screen, which could be confusing to players.

**Comment by johnnycrich** [comment] 2016-05-12 17:22
Dupe of #16

**Closed by johnnycrich** 2016-05-12 17:22 UTC
