### ISSUE TITLE
WG: game doesn't end even players have reached the target page

### ISSUE THREAD

**Issue by ritsukaBin** [engagementgamelab/emerging-citizens#105] opened 2016-07-27 18:10 UTC
Environment and setting: 2 players on MacOS chrome

The game have no response when any of the two (or both) players have found the target page, game stuck on the page of "Find the Article!". 
<img width="1440" alt="screen shot 2016-07-27 at 1 56 40 pm" src="https://cloud.githubusercontent.com/assets/20562141/17186578/d2234364-5403-11e6-9b47-83bbfa8057db.png">
<img width="1440" alt="screen shot 2016-07-27 at 1 56 52 pm" src="https://cloud.githubusercontent.com/assets/20562141/17186587/d6e46a90-5403-11e6-81ff-44c5ca2fec5a.png">

I have tried second time and same thing happened.
<img width="1440" alt="screen shot 2016-07-27 at 2 01 56 pm" src="https://cloud.githubusercontent.com/assets/20562141/17186600/dfc1d15c-5403-11e6-9b72-3a10c68376fc.png">
<img width="1440" alt="screen shot 2016-07-27 at 2 05 01 pm" src="https://cloud.githubusercontent.com/assets/20562141/17186607/e3bc2208-5403-11e6-85c7-efca62485a3a.png">

**Comment by ritsukaBin** [comment] 2016-07-27 20:08
Yet I was able to play the game on safari, it seems to be a browser-related problem

**Comment by esalling23** [comment] 2016-07-27 20:21
cannot reproduce -- closing for now

**Closed by esalling23** 2016-07-27 20:21 UTC
Labels: bug, cannot-reproduce, duplicate, WikiGeeks
