### ISSUE TITLE
WG: only two players and one remains frozen on article search screen

### ISSUE THREAD

**Issue by beccachairin** [engagementgamelab/emerging-citizens#121] opened 2016-08-01 20:28 UTC
Played a few rounds and I can't press submit on the second player's screen. Some rounds an article is assigned to this player but I can't click on the links either. 
![screen shot 2016-08-01 at 4 12 30 pm](https://cloud.githubusercontent.com/assets/20775665/17307821/fb216610-5804-11e6-8915-e8061f0e1e2e.png)

**Comment by esalling23** [comment] 2016-08-02 17:04
please provide steps for reproduction @beccachairin or @ritsukaBin 
questions - did the group screen move on?

**Comment by beccachairin** [comment] 2016-08-02 17:10
@esalling23 I think all I was doing was playing the game as normal and yes, the group screen and the first player's screen did move on.

**Comment by jpailthorpe** [comment] 2016-09-02 18:20
closing this for now because it is a bit vague, and hard to understand. Will most likely run into again if still exists

**Closed by jpailthorpe** 2016-09-02 18:20 UTC
Labels: critical, need more information, reproduce me, WikiGeeks
